version: "3.3"
services:
  rtmp:
    # build: ./rtmp
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
    container_name: rtmp_server
    volumes:
      - ./rtmp/nginx.conf:/etc/nginx/nginx.conf
      - ./rtmp/index.html:/www/index.html
      - ./hls:/tmp/hls
      - ./hls_key:/tmp/keys

  # auth:
  #   build: ./auth
  #   container_name: auth_server